// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/com/epam/elunev/entities/weatherentity.proto

package com.epam.elunev.entities;

public final class WeatherProto {
  private WeatherProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface WeatherItemOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.epam.elunev.entities.WeatherItem)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 stationnumber = 1;</code>
     */
    boolean hasStationnumber();
    /**
     * <code>required int64 stationnumber = 1;</code>
     */
    long getStationnumber();

    /**
     * <code>required int32 year = 2;</code>
     */
    boolean hasYear();
    /**
     * <code>required int32 year = 2;</code>
     */
    int getYear();

    /**
     * <code>required int32 month = 3;</code>
     */
    boolean hasMonth();
    /**
     * <code>required int32 month = 3;</code>
     */
    int getMonth();

    /**
     * <code>required int32 day = 4;</code>
     */
    boolean hasDay();
    /**
     * <code>required int32 day = 4;</code>
     */
    int getDay();

    /**
     * <code>required bool rain = 5;</code>
     */
    boolean hasRain();
    /**
     * <code>required bool rain = 5;</code>
     */
    boolean getRain();
  }
  /**
   * Protobuf type {@code com.epam.elunev.entities.WeatherItem}
   */
  public static final class WeatherItem extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.epam.elunev.entities.WeatherItem)
      WeatherItemOrBuilder {
    // Use WeatherItem.newBuilder() to construct.
    private WeatherItem(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WeatherItem(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WeatherItem defaultInstance;
    public static WeatherItem getDefaultInstance() {
      return defaultInstance;
    }

    public WeatherItem getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WeatherItem(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              stationnumber_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              year_ = input.readInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              month_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              day_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              rain_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherItem_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherItem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epam.elunev.entities.WeatherProto.WeatherItem.class, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder.class);
    }

    public static com.google.protobuf.Parser<WeatherItem> PARSER =
        new com.google.protobuf.AbstractParser<WeatherItem>() {
      public WeatherItem parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeatherItem(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherItem> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int STATIONNUMBER_FIELD_NUMBER = 1;
    private long stationnumber_;
    /**
     * <code>required int64 stationnumber = 1;</code>
     */
    public boolean hasStationnumber() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 stationnumber = 1;</code>
     */
    public long getStationnumber() {
      return stationnumber_;
    }

    public static final int YEAR_FIELD_NUMBER = 2;
    private int year_;
    /**
     * <code>required int32 year = 2;</code>
     */
    public boolean hasYear() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int32 year = 2;</code>
     */
    public int getYear() {
      return year_;
    }

    public static final int MONTH_FIELD_NUMBER = 3;
    private int month_;
    /**
     * <code>required int32 month = 3;</code>
     */
    public boolean hasMonth() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required int32 month = 3;</code>
     */
    public int getMonth() {
      return month_;
    }

    public static final int DAY_FIELD_NUMBER = 4;
    private int day_;
    /**
     * <code>required int32 day = 4;</code>
     */
    public boolean hasDay() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required int32 day = 4;</code>
     */
    public int getDay() {
      return day_;
    }

    public static final int RAIN_FIELD_NUMBER = 5;
    private boolean rain_;
    /**
     * <code>required bool rain = 5;</code>
     */
    public boolean hasRain() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required bool rain = 5;</code>
     */
    public boolean getRain() {
      return rain_;
    }

    private void initFields() {
      stationnumber_ = 0L;
      year_ = 0;
      month_ = 0;
      day_ = 0;
      rain_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStationnumber()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasYear()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMonth()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDay()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasRain()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, stationnumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt32(2, year_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, month_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, day_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, rain_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stationnumber_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, year_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, month_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, day_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, rain_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherItem parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.epam.elunev.entities.WeatherProto.WeatherItem prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.epam.elunev.entities.WeatherItem}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.epam.elunev.entities.WeatherItem)
        com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherItem_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherItem_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epam.elunev.entities.WeatherProto.WeatherItem.class, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder.class);
      }

      // Construct using com.epam.elunev.entities.WeatherProto.WeatherItem.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        stationnumber_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        year_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        month_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        day_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        rain_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherItem_descriptor;
      }

      public com.epam.elunev.entities.WeatherProto.WeatherItem getDefaultInstanceForType() {
        return com.epam.elunev.entities.WeatherProto.WeatherItem.getDefaultInstance();
      }

      public com.epam.elunev.entities.WeatherProto.WeatherItem build() {
        com.epam.elunev.entities.WeatherProto.WeatherItem result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.epam.elunev.entities.WeatherProto.WeatherItem buildPartial() {
        com.epam.elunev.entities.WeatherProto.WeatherItem result = new com.epam.elunev.entities.WeatherProto.WeatherItem(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.stationnumber_ = stationnumber_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.year_ = year_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.month_ = month_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.day_ = day_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.rain_ = rain_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epam.elunev.entities.WeatherProto.WeatherItem) {
          return mergeFrom((com.epam.elunev.entities.WeatherProto.WeatherItem)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epam.elunev.entities.WeatherProto.WeatherItem other) {
        if (other == com.epam.elunev.entities.WeatherProto.WeatherItem.getDefaultInstance()) return this;
        if (other.hasStationnumber()) {
          setStationnumber(other.getStationnumber());
        }
        if (other.hasYear()) {
          setYear(other.getYear());
        }
        if (other.hasMonth()) {
          setMonth(other.getMonth());
        }
        if (other.hasDay()) {
          setDay(other.getDay());
        }
        if (other.hasRain()) {
          setRain(other.getRain());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasStationnumber()) {
          
          return false;
        }
        if (!hasYear()) {
          
          return false;
        }
        if (!hasMonth()) {
          
          return false;
        }
        if (!hasDay()) {
          
          return false;
        }
        if (!hasRain()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epam.elunev.entities.WeatherProto.WeatherItem parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epam.elunev.entities.WeatherProto.WeatherItem) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long stationnumber_ ;
      /**
       * <code>required int64 stationnumber = 1;</code>
       */
      public boolean hasStationnumber() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 stationnumber = 1;</code>
       */
      public long getStationnumber() {
        return stationnumber_;
      }
      /**
       * <code>required int64 stationnumber = 1;</code>
       */
      public Builder setStationnumber(long value) {
        bitField0_ |= 0x00000001;
        stationnumber_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 stationnumber = 1;</code>
       */
      public Builder clearStationnumber() {
        bitField0_ = (bitField0_ & ~0x00000001);
        stationnumber_ = 0L;
        onChanged();
        return this;
      }

      private int year_ ;
      /**
       * <code>required int32 year = 2;</code>
       */
      public boolean hasYear() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int32 year = 2;</code>
       */
      public int getYear() {
        return year_;
      }
      /**
       * <code>required int32 year = 2;</code>
       */
      public Builder setYear(int value) {
        bitField0_ |= 0x00000002;
        year_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 year = 2;</code>
       */
      public Builder clearYear() {
        bitField0_ = (bitField0_ & ~0x00000002);
        year_ = 0;
        onChanged();
        return this;
      }

      private int month_ ;
      /**
       * <code>required int32 month = 3;</code>
       */
      public boolean hasMonth() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required int32 month = 3;</code>
       */
      public int getMonth() {
        return month_;
      }
      /**
       * <code>required int32 month = 3;</code>
       */
      public Builder setMonth(int value) {
        bitField0_ |= 0x00000004;
        month_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 month = 3;</code>
       */
      public Builder clearMonth() {
        bitField0_ = (bitField0_ & ~0x00000004);
        month_ = 0;
        onChanged();
        return this;
      }

      private int day_ ;
      /**
       * <code>required int32 day = 4;</code>
       */
      public boolean hasDay() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public int getDay() {
        return day_;
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public Builder setDay(int value) {
        bitField0_ |= 0x00000008;
        day_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 day = 4;</code>
       */
      public Builder clearDay() {
        bitField0_ = (bitField0_ & ~0x00000008);
        day_ = 0;
        onChanged();
        return this;
      }

      private boolean rain_ ;
      /**
       * <code>required bool rain = 5;</code>
       */
      public boolean hasRain() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required bool rain = 5;</code>
       */
      public boolean getRain() {
        return rain_;
      }
      /**
       * <code>required bool rain = 5;</code>
       */
      public Builder setRain(boolean value) {
        bitField0_ |= 0x00000010;
        rain_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool rain = 5;</code>
       */
      public Builder clearRain() {
        bitField0_ = (bitField0_ & ~0x00000010);
        rain_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.epam.elunev.entities.WeatherItem)
    }

    static {
      defaultInstance = new WeatherItem(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.epam.elunev.entities.WeatherItem)
  }

  public interface WeatherListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.epam.elunev.entities.WeatherList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem> 
        getListList();
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    com.epam.elunev.entities.WeatherProto.WeatherItem getList(int index);
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    java.util.List<? extends com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code com.epam.elunev.entities.WeatherList}
   */
  public static final class WeatherList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.epam.elunev.entities.WeatherList)
      WeatherListOrBuilder {
    // Use WeatherList.newBuilder() to construct.
    private WeatherList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private WeatherList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final WeatherList defaultInstance;
    public static WeatherList getDefaultInstance() {
      return defaultInstance;
    }

    public WeatherList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private WeatherList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<com.epam.elunev.entities.WeatherProto.WeatherItem>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(input.readMessage(com.epam.elunev.entities.WeatherProto.WeatherItem.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.epam.elunev.entities.WeatherProto.WeatherList.class, com.epam.elunev.entities.WeatherProto.WeatherList.Builder.class);
    }

    public static com.google.protobuf.Parser<WeatherList> PARSER =
        new com.google.protobuf.AbstractParser<WeatherList>() {
      public WeatherList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeatherList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<WeatherList> getParserForType() {
      return PARSER;
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem> list_;
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    public java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem> getListList() {
      return list_;
    }
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    public java.util.List<? extends com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    public com.epam.elunev.entities.WeatherProto.WeatherItem getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
     */
    public com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private void initFields() {
      list_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getListCount(); i++) {
        if (!getList(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.epam.elunev.entities.WeatherProto.WeatherList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.epam.elunev.entities.WeatherProto.WeatherList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.epam.elunev.entities.WeatherList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.epam.elunev.entities.WeatherList)
        com.epam.elunev.entities.WeatherProto.WeatherListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.epam.elunev.entities.WeatherProto.WeatherList.class, com.epam.elunev.entities.WeatherProto.WeatherList.Builder.class);
      }

      // Construct using com.epam.elunev.entities.WeatherProto.WeatherList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.epam.elunev.entities.WeatherProto.internal_static_com_epam_elunev_entities_WeatherList_descriptor;
      }

      public com.epam.elunev.entities.WeatherProto.WeatherList getDefaultInstanceForType() {
        return com.epam.elunev.entities.WeatherProto.WeatherList.getDefaultInstance();
      }

      public com.epam.elunev.entities.WeatherProto.WeatherList build() {
        com.epam.elunev.entities.WeatherProto.WeatherList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.epam.elunev.entities.WeatherProto.WeatherList buildPartial() {
        com.epam.elunev.entities.WeatherProto.WeatherList result = new com.epam.elunev.entities.WeatherProto.WeatherList(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.epam.elunev.entities.WeatherProto.WeatherList) {
          return mergeFrom((com.epam.elunev.entities.WeatherProto.WeatherList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.epam.elunev.entities.WeatherProto.WeatherList other) {
        if (other == com.epam.elunev.entities.WeatherProto.WeatherList.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getListCount(); i++) {
          if (!getList(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.epam.elunev.entities.WeatherProto.WeatherList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.epam.elunev.entities.WeatherProto.WeatherList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<com.epam.elunev.entities.WeatherProto.WeatherItem>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          com.epam.elunev.entities.WeatherProto.WeatherItem, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder, com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder> listBuilder_;

      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public com.epam.elunev.entities.WeatherProto.WeatherItem getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder setList(
          int index, com.epam.elunev.entities.WeatherProto.WeatherItem value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder setList(
          int index, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder addList(com.epam.elunev.entities.WeatherProto.WeatherItem value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder addList(
          int index, com.epam.elunev.entities.WeatherProto.WeatherItem value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder addList(
          com.epam.elunev.entities.WeatherProto.WeatherItem.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder addList(
          int index, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.epam.elunev.entities.WeatherProto.WeatherItem> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public com.epam.elunev.entities.WeatherProto.WeatherItem.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public java.util.List<? extends com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public com.epam.elunev.entities.WeatherProto.WeatherItem.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.epam.elunev.entities.WeatherProto.WeatherItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public com.epam.elunev.entities.WeatherProto.WeatherItem.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.epam.elunev.entities.WeatherProto.WeatherItem.getDefaultInstance());
      }
      /**
       * <code>repeated .com.epam.elunev.entities.WeatherItem list = 1;</code>
       */
      public java.util.List<com.epam.elunev.entities.WeatherProto.WeatherItem.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          com.epam.elunev.entities.WeatherProto.WeatherItem, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder, com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              com.epam.elunev.entities.WeatherProto.WeatherItem, com.epam.elunev.entities.WeatherProto.WeatherItem.Builder, com.epam.elunev.entities.WeatherProto.WeatherItemOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.epam.elunev.entities.WeatherList)
    }

    static {
      defaultInstance = new WeatherList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.epam.elunev.entities.WeatherList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_elunev_entities_WeatherItem_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_epam_elunev_entities_WeatherItem_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_epam_elunev_entities_WeatherList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_epam_elunev_entities_WeatherList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n:src/main/java/com/epam/elunev/entities" +
      "/weatherentity.proto\022\030com.epam.elunev.en" +
      "tities\"\\\n\013WeatherItem\022\025\n\rstationnumber\030\001" +
      " \002(\003\022\014\n\004year\030\002 \002(\005\022\r\n\005month\030\003 \002(\005\022\013\n\003day" +
      "\030\004 \002(\005\022\014\n\004rain\030\005 \002(\010\"B\n\013WeatherList\0223\n\004l" +
      "ist\030\001 \003(\0132%.com.epam.elunev.entities.Wea" +
      "therItemB\016B\014WeatherProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_epam_elunev_entities_WeatherItem_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_epam_elunev_entities_WeatherItem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_epam_elunev_entities_WeatherItem_descriptor,
        new java.lang.String[] { "Stationnumber", "Year", "Month", "Day", "Rain", });
    internal_static_com_epam_elunev_entities_WeatherList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_epam_elunev_entities_WeatherList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_epam_elunev_entities_WeatherList_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
